---
projecttitle: 'Encouraging uptake of the recommended vaccine sequence for seniors in Louisiana'
projectcode: 1738
author: Jake Bowers
date: "`r format(Sys.time(), '%a %b %d %X %Y')`"
output:
  html_document:
    code_folding: hide
    toc: true
    fig_caption: true
    css: oes.css
  pdf_document:
    fig_caption: true
    fig_height: 7
    fig_width: 7
    keep_tex: yes
    latex_engine: xelatex
    md_extensions: +autolink_bare_uris+tex_math_dollars
    number_sections: yes
    template: oesreanalysisrecord.latex
---

<!-- Much of the intro text from the Project Summary in the Team Drive -->

```{r setup, eval=FALSE,results='hide', message=FALSE, warning=FALSE, echo=FALSE}
# Clear environment, set working directory, load packages & data
rm(list = ls())
source("setup.R")
```

# How this document is to be used: 

*This document is associated with the "Reanalysis" gate and is intended
to be the record of the reanalysis of project data. When the reanalyst
has completed this document and is ready for a discussion with the
project Lead to discuss final results, they will schedule a conversation
to reconcile the two analyses.*

# Analysis

## Background:

*The reanalyst's understanding of the study design, objectives, and planned analysis are as follows:*

## Methods:

*Describe all analyses conducted in sufficient detail that they could be replicated exactly. These should match what was proposed in the Analysis Plan. Any departures should be noted below (see section Departures from Analysis Plan). Include a link to your code.*

## Results:

*Include results of all analyses described in the Methods section,
including checks on model assumptions etc. Include tables \& graphs. If
results are contained in other files, include links to those files
here.*

## Departures from Analysis Plan:

*Describe any departures from the Analysis Plan, including any exploratory analyses. Include rationales for these departures and statistical adjustments made to account for unplanned tests.*

## Limitations:

*Describe any limitations associated with the analysis, including any
limitations that only became apparent during the course of the
analysis.*

# Exploratory Analysis

*Describe any exploratory analysis completed by the reanalyst.*

# References
